name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Configure Git author
        run: |
          git config --local user.email "amar.codingenthusiast@gmail.com"
          git config --local user.name "Amar Kumar"

      - name: Deploy to GitHub Pages
        run: |
          npm run deploy
